import FooterComp from "@/ui/components/footer";
import PropTypes from "prop-types";


export const metadata = {
    title: "CampusSync",
    description: "Generated by create next app",
};

export default function AuthLayout({ children }) {
    return (
        < >
            {children}
            <FooterComp />
        </>
    );
}

AuthLayout.propTypes = {
    children: PropTypes.node.isRequired,
};