import "./globals.css";
import PropTypes from "prop-types";
import { ToastContainer } from "react-toastify";
import NextTopLoader from "nextjs-toploader";


export const metadata = {
    title: "CampusSync",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <NextTopLoader
                    color="#000fff"
                    showSpinner={false}
                />
                <ToastContainer
                    autoClose={1800}
                    newestOnTop={true}
                    closeOnClick
                    rtl={false}
                />
                {children}
            </body>
        </html>
    );
}

RootLayout.propTypes = {
    children: PropTypes.node.isRequired,
};